# Generated by Django 5.2.7 on 2025-11-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('tenants', '0002_module_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module__code', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='systemmodulepermission',
            options={'ordering': ['resource__name', 'action'], 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.RenameIndex(
            model_name='systemmodulepermission',
            new_name='tenants_sys_resourc_6f417a_idx',
            old_name='tenants_mod_resourc_cec6fc_idx',
        ),
        migrations.RenameIndex(
            model_name='systemmodulepermission',
            new_name='tenants_sys_codenam_6afa98_idx',
            old_name='tenants_mod_codenam_f5a56b_idx',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='modules',
        ),
        migrations.RenameModel(
            old_name='ModulePermission',
            new_name='SystemModulePermission',
        ),
        migrations.AddField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='tenants.module'),
        ),
        migrations.AlterField(
            model_name='systemmodulepermission',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='tenants.submodule'),
        ),
    ]
