# Generated by Django 5.2.7 on 2025-12-13 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0005_remove_kpiscore_kpi_delete_kpi_delete_kpiscore'),
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better')], default='higher_is_better', max_length=32)),
                ('indicator_type', models.CharField(choices=[('input', 'Input'), ('process', 'Process'), ('output', 'Output'), ('outcome', 'Outcome')], max_length=32)),
                ('reporting_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('scoring_config', models.JSONField(default=dict)),
                ('formula', models.TextField(blank=True, help_text='Optional expression/DSL for composite or computed KPIs')),
                ('is_composite', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='departments.departmentobjective')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='indicators.kpi')),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategy.financialyear')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategy.objective')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='departments.teamobjective')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('actual', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('target', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('baseline', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='KPIScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('weighted_score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('details', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('kpi_value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='indicators.kpivalue')),
            ],
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['code'], name='indicators__code_9d555e_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['indicator_type'], name='indicators__indicat_34257d_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['reporting_period'], name='indicators__reporti_0ff561_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['kpi', 'period_start'], name='indicators__kpi_id_4648d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpivalue',
            unique_together={('kpi', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='kpiscore',
            index=models.Index(fields=['kpi_value'], name='indicators__kpi_val_f9831f_idx'),
        ),
    ]
