# Generated by Django 5.2.7 on 2025-11-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamobjective',
            name='team_objective_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamobjective',
            name='team_objective_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamobjective',
            name='team_objective_target',
            field=models.TextField(blank=True),
        ),
    ]
