# Generated by Django 5.2.7 on 2025-10-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teamobjective',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='teamobjective',
            name='kpi',
        ),
        migrations.AddField(
            model_name='kpi',
            name='department_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='departments.departmentobjective'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategy.financialyear'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., monthly, quarterly', max_length=50),
        ),
        migrations.AddField(
            model_name='kpi',
            name='level',
            field=models.CharField(choices=[('strategic', 'Strategic'), ('department', 'Department'), ('team', 'Team')], default='team', max_length=20),
        ),
        migrations.AddField(
            model_name='kpi',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='status',
            field=models.CharField(blank=True, help_text='e.g., On Track, Behind', max_length=50),
        ),
        migrations.AddField(
            model_name='kpi',
            name='team_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='departments.teamobjective'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategy.objective'),
        ),
        migrations.CreateModel(
            name='KPIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, help_text='e.g., 2025-Q1, 2025-01', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='departments.kpi')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
