# Generated by Django 5.2.7 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_kpi_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentobjective',
            name='composite_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Composite weight of the objective', max_digits=5),
        ),
    ]
