# Generated by Django 5.2.7 on 2025-11-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_teamobjective_team_objective_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentobjective',
            name='target',
        ),
        migrations.RemoveField(
            model_name='teamobjective',
            name='team_objective_target',
        ),
        migrations.AddField(
            model_name='departmentobjective',
            name='objective_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='teamobjective',
            name='objective_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title or position', max_length=255)),
                ('is_department_head', models.BooleanField(default=False, help_text='Whether this employee is the head of the department. Only one employee per department can be head.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department')),
                ('related_user', models.OneToOneField(help_text='The user account associated with this employee', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Optional team assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.team')),
            ],
            options={
                'ordering': ['-is_department_head', 'job_title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeReportingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('line_manager', 'Line Manager'), ('functional_manager', 'Functional Manager'), ('supervisor', 'Supervisor')], help_text='Type of reporting relationship', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The employee who reports', on_delete=django.db.models.deletion.CASCADE, related_name='reporting_lines', to='departments.employee')),
                ('reports_to', models.ForeignKey(help_text='The employee being reported to', on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='departments.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_department_head'], name='departments_departm_8582e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_department_head', True)), fields=('department',), name='unique_department_head'),
        ),
        migrations.AddIndex(
            model_name='employeereportingline',
            index=models.Index(fields=['employee', 'relationship_type'], name='departments_employe_962c71_idx'),
        ),
        migrations.AddIndex(
            model_name='employeereportingline',
            index=models.Index(fields=['reports_to', 'relationship_type'], name='departments_reports_00705f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeereportingline',
            unique_together={('employee', 'reports_to', 'relationship_type')},
        ),
    ]
