# Generated by Django 5.2.7 on 2025-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_remove_departmentobjective_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentobjective',
            name='department_objective_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
