# Generated by Django 5.2.7 on 2025-12-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_departmentobjective_department_objective_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiscore',
            name='kpi',
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.DeleteModel(
            name='KPIScore',
        ),
    ]
